theme: jekyll-theme-primer

exclude:
  - node_modules
  - scripts
  - update-table-of-contents.js

title: The Riddler Solutions
description: Solutions to FiveThiryEight's weekly The Riddler posts.

data:
  projects:
    - sample 1
    - sample 2
    - sample 3
    - nested:
      - isn't this cool?
